version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ratingus-network
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.crt:/etc/ssl/cert.crt:ro;
      - ./nginx/private.key:/etc/ssl/private.key:ro;

networks:
  ratingus-network:
    external: true
